name       : pentobi
version    : '18.0'
release    : 5
source     :
    - https://liquidtelecom.dl.sourceforge.net/project/pentobi/18.0/pentobi-18.0.tar.xz : de85eec2ab884615f2b384381402ccea9cccaafada183a330454c6ce3dd49b36
homepage   : https://pentobi.sourceforge.io/
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Pentobi is a computer opponent for the board game Blokus
description: |
    Pentobi is a computer opponent for the board game Blokus. Supported game variants: Classic, Duo, Trigon, Junior, Nexos, GembloQ, Callisto. Strong Blokus engine with 9 different playing levels. Player rating by playing rated games against the computer. Game analysis function. Save and load games in Smart Game Format including comments and move variations. System requirements: 1 GB RAM, 1 GHz CPU (4 GB RAM, 2.5 GHz dual-core or faster CPU recommended for playing level 9)
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebView)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %cmake \
        -DDOCBOOKXSL_DIR=/usr/share/xml/docbook/xsl-stylesheets-1.79.2/ \
        -DMETAINFO_ITS=/usr/share/gettext-0.20/its
build      : |
    %make
install    : |
    %make_install
