name       : pentobi
version    : 13.0
release    : 1
source     :
    - https://netcologne.dl.sourceforge.net/project/pentobi/13.0/pentobi-13.0.tar.xz : 955a384b9b577d2d216f4e3b864e8e1968036188931e466323e301803d0c9fe1
license    : GPL-3.0 
component  : games.puzzle
summary    : Pentobi is a computer opponent for the board game Blokus
description: |
    Pentobi is a computer opponent for the board game Blokus. Supported game variants: Classic, Duo, Trigon, Junior, Nexos, GembloQ, Callisto. Strong Blokus engine with 9 different playing levels. Player rating by playing rated games against the computer. Game analysis function. Save and load games in Smart Game Format including comments and move variations. System requirements: 1 GB RAM, 1 GHz CPU (4 GB RAM, 2.5 GHz dual-core or faster CPU recommended for playing level 9)
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
